print("Hello & welcome to my first python program.")
nameInput = input("Whats your name?")
input = input("Hi " + nameInput +". How old are you?")
print("You are " + input + " years old.")
print("You've joined the programming party at just the right time. Welcome :)")